<?php
switch (@$_GET['pagina']) 

{
 case "" : include("inicial.php");
                         break;
case "mensagemenviada" : include("mail/sucesso.php");
         break;
case "atualizacao" : include("atualizacao.php");
         break;						 
case "fotos" : include("fotos.php");
         break;
case "atividades" : include("atividades.php");
                         break;
case "gregeo" : include("gregeo.php");
                         break;
 case "espeleologia" : include("espeleologia.php");
				break;
 case "dicas" : include("dicasparaatividade.php");
				break;
 case "estatuto" : include("estatuto.php");
				break;
 case "contato" : include("contato.php");
				break;
 case "legislacao" : include("legislacao.php");
				break;
 case "inicial" : include("inicial.php");
				break;
 case "morrodapedreira" : include("morrodapedreira.php");
				break;
 case "jan2014" : include("atividades/2014/janeiro.php");
					break;
case "2nov2013" : include("atividades/2013/novembro2.php");
				break;
case "1nov2013" : include("atividades/2013/novembro1.php");
				break;	
case "out2013" : include("atividades/2013/outubro.php");
				break;
case "2set2013" : include("atividades/2013/setembro2.php");
				break;
case "1set2013" : include("atividades/2013/setembro1.php");
				break;				
case "set2013" : include("atividades/2013/setembro.php");
				break;	
 case "mai2013" : include("atividades/2013/maio.php");
				break;					
 case "abr2013" : include("atividades/2013/abril.php");
				break;	
 case "mar2013" : include("atividades/2013/marco.php");
				break;				
 case "fev2013" : include("atividades/2013/fevereiro.php");
				break;
 case "jan2013" : include("atividades/2013/janeiro.php");
				break;
 case "dez2012" : include("atividades/2012/dezembro.php");
				break;					
 case "nov2012" : include("atividades/2012/novembro.php");
				break;					
 case "out2012" : include("atividades/2012/outubro.php");
				break;				
 case "set2012" : include("atividades/2012/setembro.php");
				break;
 case "ago2012" : include("atividades/2012/agosto.php");
				break;
 case "ago2011" : include("atividades/2011/agosto.php");
				break;		
 case "mai2011" : include("atividades/2011/maio.php");
				break;
 case "mar2011" : include("atividades/2011/marco.php");
				break;	
 case "abr2008" : include("atividades/2008/abril.php");
				break;	

 case "nov2007" : include("atividades/2007/novembro.php");
				break;
 case "jul2007" : include("atividades/2007/julho.php");
				break;
 case "jun2007" : include("atividades/2007/junho.php");
				break;
 case "mai2007" : include("atividades/2007/maio.php");
				break;
 case "buracodasararasantigo" : include("antigas/buracodasararas.php");
				break;					
 case "abismodocagadao" : include("antigas/abismodocagadao.php");
				break;					
 case "cbe1993" : include("antigas/cbe1993.php");
				break;					
 case "cbe1989" : include("antigas/cbe1989.php");
				break;					
 case "expedicoesantigas" : include("antigas.php");
				break;					
 case "primeirassaidas" : include("antigas/primeirassaidas.php");
				break;	
 case "expedicaogoias" : include("antigas/expedicaogoias.php");
				break;	
 case "saidavazante" : include("antigas/vazante.php");
				break;					
default: include("erro.php")	;				
				
}
?>